language: node_js
node_js:
  - '9'
install:
  - npm ci
addons:
  sonarcloud:
    organization: janedoegva-github
    token: ${SONAR_TOKEN}
    branches:
      - master
script:
  - npm -v
  - npm run ci
  - sonar-scanner
