language: node_js
node_js:
  - '9'
before_install:
  - npm i -g npm@6.1.0
install:
  - npm ci
cache:
  directories:
    - node_modules
    - npm run ci
addons:
  sonarcloud:
    organization: janedoegva-github
    token: ${SONAR_TOKEN}
    branches:
      - master
script:
  - npm -v
  - npm run ci
  - sonar-scanner
