language: node_js
dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: janedoegva-github
    token: ${SONAR_TOKEN}
    branches:
      - master
jdk:
  - oraclejdk8
install:
  - npm install
script:
  - sonar-scanner
