language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: janedoegva-github
    token: ${SONAR_TOKEN}
    branches:
      - master
script:
  - npm run ci
  - sonar-scanner
