language: node_js
node_js:
  - '9.8.0'
install:
  - npm ci
cache:
  directories:
    - node_modules
    - npm run ci
addons:
  sonarcloud:
    organization: janedoegva-github
    token: ${SONAR_TOKEN}
    branches:
      - master
script:
  - npm run ci
  - sonar-scanner
