export const LOAD_IS_PROCESSING = 'HOME::LOAD_IS_PROCESSING';
export const LOAD_HAS_ERRORED = 'HOME::LOAD_HAS_ERRORED';
export const LOAD_SUCCESS = 'HOME::LOAD_SUCCESS';
export const UPDATE_IS_PROCESSING = 'HOME::UPDATE_IS_PROCESSING';
export const UPDATE_HAS_ERRORED = 'HOME::UPDATE_HAS_ERRORED';
export const UPDATE_SUCCESS = 'HOME::UPDATE_SUCCESS';
