export const CREATE_ACT_TRACKER = 'CREATE_ACT_TRACKER';
export const CREATE_IS_PROCESSING = 'CREATE_IS_PROCESSING';
export const CREATE_ITEM_HAS_ERRORED = 'CREATE_ITEM_HAS_ERRORED';
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';
