export const SUBSCRIBE_IS_PROCESSING = 'SUBSCRIBE::SUBSCRIBE_IS_PROCESSING';
export const SUBSCRIBE_HAS_ERRORED = 'SUBSCRIBE::SUBSCRIBE_HAS_ERRORED';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE::SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_MOUNT = 'SUBSCRIBE::MOUNT';
