export const CREATE_IS_PROCESSING = 'SUBSCRIBE::CREATE_IS_PROCESSING';
export const CREATE_ITEM_HAS_ERRORED = 'SUBSCRIBE::CREATE_ITEM_HAS_ERRORED';
export const ITEM_CREATE_SUCCESS = 'SUBSCRIBE::ITEM_CREATE_SUCCESS';
